#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
# 
#    http://shiny.rstudio.com/
#

library(ggplot2)

library(rlang)
library(shiny)
library(shinycssloaders)
library(shinythemes)
library(dplyr)

# Define UI for application that draws a histogram
ui = fluidPage(
  theme = shinytheme("cerulean"),
  navbarPage("West Brook Growth Model Predictions " ,
             tabPanel("Main Effects" ,
                      # titlePanel("Main Effects"),
                      fluidRow(
                        column(3,
                               wellPanel(
                                 selectInput('dataType1' , 
                                             'Data Type' , 
                                             c( 'Mean Growth mm/d' , 
                                                'Standard Deviation' , 
                                                'CV') ,
                                             'predGr')),
                               wellPanel(
                                 radioButtons('variable' , 
                                              'Variable To Display' , 
                                              c('Stream Temperature' = 'temp' , 
                                                'Stream Flow' = 'flow' , 
                                                'Estimated Abundance' = 'count' , 
                                                'Fish Length' = 'length') , 
                                              'temp')),
                               wellPanel(
                               
                                  
                                   checkboxGroupInput('specieSA' , 
                                                      'Species' , 
                                                      c('Brook Trout' , 
                                                        'Brown Trout'  , 
                                                        'Atlantic Salmon' ), 
                                                      'Brook Trout') ,
                                 splitLayout(
                                   checkboxGroupInput("riverA" ,
                                                      "Tributary" , 
                                                      c("West Brook" = "west brook" , 
                                                        "Open Large" = "wb jimmy" , 
                                                        "Isolated Small" = "wb obear" , 
                                                        "Open Small" = "wb mitchell") ,
                                                      "west brook" ) ,
                                   checkboxGroupInput("seasoNA" ,
                                                      "Season" ,
                                                      c('Spring' = '1' ,
                                                        'Summer' = '2' ,
                                                        'Fall' = '3' ,
                                                        'Winter' = '4') ,
                                                      '1' )),
                                 sliderInput("slider2A", label = h4("Iterations"), min = 10, 
                                             max = 1500, value =  1000)
                               )),
                        
                        # Show a plot of the generated distribution
                        column(9,
                               
                               conditionalPanel(condition = "input.variable == 'temp'" ,
                                                plotOutput("plot1A", height = "700px")),
                               
                               conditionalPanel(condition = "input.variable == 'flow'" ,                 
                                                plotOutput("plot2A", height = "700px")),
                               conditionalPanel(condition = "input.variable == 'count'" ,                 
                                                plotOutput("plot3A", height = "700px")),
                               conditionalPanel(condition = "input.variable == 'length'" ,                 
                                                plotOutput("plot4A", height = "700px")))
                        #ggvisOutput("plot2A")))
                        #ggvisOutput("plot3A")
                      )
                      
             ),
             tabPanel("Interactions" , 
                      
                      # Application title
                      #titlePanel("Interactions"),
                      
                      # Sidebar with a slider input for number of bins 
                      fluidRow(
                        column(3,
                               
                               
                               wellPanel(
                                 selectInput('dataType2' , 
                                             'Data Type' , 
                                             c( 'Mean Growth mm/d' , 
                                                'Standard Deviation' , 
                                                'CV') ,
                                             'predGr')
                               ),
                               fluidRow(
                                 column(3 , tags$h3("Data_Filter"))),
                               conditionalPanel(condition = "input.facet1 == 'Age'",
                                                conditionalPanel(condition = "input.facet2 == 'River'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageAgeRiver" , 
                                                                                        "Age" ,
                                                                                        c("Young of The Year" = "0", 
                                                                                          "Adult" =  "1") ,
                                                                                        "1"),
                                                                     radioButtons('speciesAgeRiver' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverAgeRiver" ,
                                                                                        "River" , 
                                                                                        c("West Brook" = "west brook" , 
                                                                                          "Open Large" = "wb jimmy" , 
                                                                                          "Isolated Small" = "wb obear" , 
                                                                                          "Open Small" = "wb mitchell") ,
                                                                                        "west brook" ) ,
                                                                     radioButtons("seasonAgeRiver" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               conditionalPanel(condition = "input.facet1 == 'Age'",
                                                conditionalPanel(condition = "input.facet2 == 'Season'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageAgeSeason" , 
                                                                                        "Age" ,
                                                                                        c("Young of The Year" = "0", 
                                                                                          "Adult" =  "1") ,
                                                                                        "1"),
                                                                     radioButtons('speciesAgeSeason' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverAgeSeason" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     checkboxGroupInput("seasonAgeSeason" ,
                                                                                        "Season" ,
                                                                                        c('Spring' = '1' ,
                                                                                          'Summer' = '2' ,
                                                                                          'Fall' = '3' ,
                                                                                          'Winter' = '4') ,
                                                                                        '1' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'Age'",
                                                conditionalPanel(condition = "input.facet2 == 'Species'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageAgeSpecies" , 
                                                                                        "Age" ,
                                                                                        c("Young of The Year" = "0", 
                                                                                          "Adult" =  "1") ,
                                                                                        "1"),
                                                                     checkboxGroupInput('speciesAgeSpecies' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' = 'bkt', 
                                                                                          'Brown Trout' = 'bnt' , 
                                                                                          'Atlantic Salmon' = 'ats'),
                                                                                        'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverAgeSpecies" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     radioButtons("seasonAgeSpecies" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'River'",
                                                conditionalPanel(condition = "input.facet2 == 'Age'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageRiverAge" , 
                                                                                        "Age" ,
                                                                                        c("Young of The Year" = "0", 
                                                                                          "Adult" =  "1") ,
                                                                                        "1"),
                                                                     radioButtons('speciesRiverAge' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverRiverAge" ,
                                                                                        "River" , 
                                                                                        c("West Brook" = "west brook" , 
                                                                                          "Open Large" = "wb jimmy" , 
                                                                                          "Isolated Small" = "wb obear" , 
                                                                                          "Open Small" = "wb mitchell") ,
                                                                                        "west brook" ) ,
                                                                     radioButtons("seasonRiverAge" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               conditionalPanel(condition = "input.facet1 == 'River'",
                                                conditionalPanel(condition = "input.facet2 == 'Season'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageRiverSeason" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     radioButtons('speciesRiverSeason' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverRiverSeason" ,
                                                                                        "River" , 
                                                                                        c("West Brook" = "west brook" , 
                                                                                          "Open Large" = "wb jimmy" , 
                                                                                          "Isolated Small" = "wb obear" , 
                                                                                          "Open Small" = "wb mitchell") ,
                                                                                        "west brook" ) ,
                                                                     checkboxGroupInput("seasonRiverSeason" ,
                                                                                        "Season" ,
                                                                                        c('Spring' = '1' ,
                                                                                          'Summer' = '2' ,
                                                                                          'Fall' = '3' ,
                                                                                          'Winter' = '4') ,
                                                                                        '1' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'River'",
                                                conditionalPanel(condition = "input.facet2 == 'Species'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageRiverSpecies" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     checkboxGroupInput('speciesRiverSpecies' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' = 'bkt', 
                                                                                          'Brown Trout' = 'bnt' , 
                                                                                          'Atlantic Salmon' = 'ats'),
                                                                                        'bkt' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverRiverSpecies" ,
                                                                                        "River" , 
                                                                                        c("West Brook" = "west brook" , 
                                                                                          "Open Large" = "wb jimmy" , 
                                                                                          "Isolated Small" = "wb obear" , 
                                                                                          "Open Small" = "wb mitchell") ,
                                                                                        "west brook" ) ,
                                                                     radioButtons("seasonRiverSpecies" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               
                               
                               ### Season
                               
                               conditionalPanel(condition = "input.facet1 == 'Season'",
                                                conditionalPanel(condition = "input.facet2 == 'Age'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageSeasonAge" , 
                                                                                        "Age" ,
                                                                                        c("Young of The Year" = "0", 
                                                                                          "Adult" =  "1") ,
                                                                                        "1"),
                                                                     radioButtons('speciesSeasonAge' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSeasonAge" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     checkboxGroupInput("seasonSeasonAge" ,
                                                                                        "Season" ,
                                                                                        c('Spring' = '1' ,
                                                                                          'Summer' = '2' ,
                                                                                          'Fall' = '3' ,
                                                                                          'Winter' = '4') ,
                                                                                        '1' ))))),
                               conditionalPanel(condition = "input.facet1 == 'Season'",
                                                conditionalPanel(condition = "input.facet2 == 'River'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSeasonRiver" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     radioButtons('speciesSeasonRiver' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverSeasonRiver" ,
                                                                                        "River" , 
                                                                                        c("West Brook" = "west brook" , 
                                                                                          "Open Large" = "wb jimmy" , 
                                                                                          "Isolated Small" = "wb obear" , 
                                                                                          "Open Small" = "wb mitchell") ,
                                                                                        "west brook" ) ,
                                                                     checkboxGroupInput("seasonSeasonRiver" ,
                                                                                        "Season" ,
                                                                                        c('Spring' = '1' ,
                                                                                          'Summer' = '2' ,
                                                                                          'Fall' = '3' ,
                                                                                          'Winter' = '4') ,
                                                                                        '1' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'Season'",
                                                conditionalPanel(condition = "input.facet2 == 'Species'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSeasonSpecies" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     checkboxGroupInput('speciesSeasonSpecies' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' = 'bkt', 
                                                                                          'Brown Trout' = 'bnt' , 
                                                                                          'Atlantic Salmon' = 'ats'),
                                                                                        'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSeasonSpecies" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     checkboxGroupInput("seasonSeasonSpecies" ,
                                                                                        "Season" ,
                                                                                        c('Spring' = '1' ,
                                                                                          'Summer' = '2' ,
                                                                                          'Fall' = '3' ,
                                                                                          'Winter' = '4') ,
                                                                                        '1' ))))),
                               
                               
                               
                               
                               conditionalPanel(condition = "input.facet1 == 'Species'",
                                                conditionalPanel(condition = "input.facet2 == 'Age'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageSpeciesAge" , 
                                                                                        "Age" ,
                                                                                        c("Young of The Year" = "0", 
                                                                                          "Adult" =  "1") ,
                                                                                        "1"),
                                                                     checkboxGroupInput('speciesSpeciesAge' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' = 'bkt', 
                                                                                          'Brown Trout' = 'bnt' , 
                                                                                          'Atlantic Salmon' = 'ats'),
                                                                                        'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSpeciesAge" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     radioButtons("seasonSpeciesAge" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               conditionalPanel(condition = "input.facet1 == 'Species'",
                                                conditionalPanel(condition = "input.facet2 == 'River'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSpeciesRiver" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     checkboxGroupInput('speciesSpeciesRiver' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' = 'bkt', 
                                                                                          'Brown Trout' = 'bnt' , 
                                                                                          'Atlantic Salmon' = 'ats'),
                                                                                        'bkt' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverSpeciesRiver" ,
                                                                                        "River" , 
                                                                                        c("West Brook" = "west brook" , 
                                                                                          "Open Large" = "wb jimmy" , 
                                                                                          "Isolated Small" = "wb obear" , 
                                                                                          "Open Small" = "wb mitchell") ,
                                                                                        "west brook" ) ,
                                                                     radioButtons("seasonSpeciesRiver" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'Species'",
                                                conditionalPanel(condition = "input.facet2 == 'Season'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSpeciesSeason" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     checkboxGroupInput('speciesSpeciesSeason' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' = 'bkt', 
                                                                                          'Brown Trout' = 'bnt' , 
                                                                                          'Atlantic Salmon' = 'ats'),
                                                                                        'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSpeciesSeason" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     checkboxGroupInput("seasonSpeciesSeason" ,
                                                                                        "Season" ,
                                                                                        c('Spring' = '1' ,
                                                                                          'Summer' = '2' ,
                                                                                          'Fall' = '3' ,
                                                                                          'Winter' = '4') ,
                                                                                        '1' ))))),
                               
                               
                               
                               
                               conditionalPanel(condition = "input.facet1 == 'None'",
                                                conditionalPanel(condition = "input.facet2 == 'Age'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageNoneAge" , 
                                                                                        "Age" ,
                                                                                        c("Young of The Year" = "0", 
                                                                                          "Adult" =  "1") ,
                                                                                        "1"),
                                                                     radioButtons('speciesNoneAge' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverNoneAge" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     radioButtons("seasonNoneAge" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               conditionalPanel(condition = "input.facet1 == 'None'",
                                                conditionalPanel(condition = "input.facet2 == 'River'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageNoneRiver" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     radioButtons('speciesNoneRiver' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverNoneRiver" ,
                                                                                        "River" , 
                                                                                        c("West Brook" = "west brook" , 
                                                                                          "Open Large" = "wb jimmy" , 
                                                                                          "Isolated Small" = "wb obear" , 
                                                                                          "Open Small" = "wb mitchell") ,
                                                                                        "west brook" ) ,
                                                                     radioButtons("seasonNoneRiver" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'None'",
                                                conditionalPanel(condition = "input.facet2 == 'Season'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageNoneSeason" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     radioButtons('speciesNoneSeason' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverNoneSeason" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     checkboxGroupInput("seasonNoneSeason" ,
                                                                                        "Season" ,
                                                                                        c('Spring' = '1' ,
                                                                                          'Summer' = '2' ,
                                                                                          'Fall' = '3' ,
                                                                                          'Winter' = '4') ,
                                                                                        '1' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'None'",
                                                conditionalPanel(condition = "input.facet2 == 'Species'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageNoneSpecies" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     checkboxGroupInput('speciesNoneSpecies' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' = 'bkt', 
                                                                                          'Brown Trout' = 'bnt' , 
                                                                                          'Atlantic Salmon' = 'ats'),
                                                                                        'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverNoneSpecies" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     radioButtons("seasonNoneSpecies" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               
                               
                               
                               
                               conditionalPanel(condition = "input.facet1 == 'Age'",
                                                conditionalPanel(condition = "input.facet2 == 'None'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageAgeNone" , 
                                                                                        "Age" ,
                                                                                        c("Young of The Year" = "0", 
                                                                                          "Adult" =  "1") ,
                                                                                        "1"),
                                                                     radioButtons('speciesAgeNone' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverAgeNone" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     radioButtons("seasonAgeNone" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               conditionalPanel(condition = "input.facet1 == 'River'",
                                                conditionalPanel(condition = "input.facet2 == 'None'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageRiverNone" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     radioButtons('speciesRiverNone' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverRiverNone" ,
                                                                                        "River" , 
                                                                                        c("West Brook" = "west brook" , 
                                                                                          "Open Large" = "wb jimmy" , 
                                                                                          "Isolated Small" = "wb obear" , 
                                                                                          "Open Small" = "wb mitchell") ,
                                                                                        "west brook" ) ,
                                                                     radioButtons("seasonRiverNone" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'Season'",
                                                conditionalPanel(condition = "input.facet2 == 'None'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSeasonNone" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     radioButtons('speciesSeasonNone' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSeasonNone" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     checkboxGroupInput("seasonSeasonNone" ,
                                                                                        "Season" ,
                                                                                        c('Spring' = '1' ,
                                                                                          'Summer' = '2' ,
                                                                                          'Fall' = '3' ,
                                                                                          'Winter' = '4') ,
                                                                                        '1' ))))),
                               conditionalPanel(condition = "input.facet1 == 'Species'",
                                                conditionalPanel(condition = "input.facet2 == 'None'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSpeciesNone" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     checkboxGroupInput('speciesSpeciesNone' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' = 'bkt', 
                                                                                          'Brown Trout' = 'bnt' , 
                                                                                          'Atlantic Salmon' = 'ats'),
                                                                                        'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSpeciesNone" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     radioButtons("seasonSpeciesNone" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'None'",
                                                conditionalPanel(condition = "input.facet2 == 'None'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageNoneNone" , 
                                                                                  "Age" ,
                                                                                  c("Young of The Year" = "0", 
                                                                                    "Adult" =  "1") ,
                                                                                  "1"),
                                                                     radioButtons('speciesNoneNone' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' = 'bkt', 
                                                                                    'Brown Trout' = 'bnt' , 
                                                                                    'Atlantic Salmon' = 'ats'),
                                                                                  'bkt' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverNoneNone" ,
                                                                                  "River" , 
                                                                                  c("West Brook" = "west brook" , 
                                                                                    "Open Large" = "wb jimmy" , 
                                                                                    "Isolated Small" = "wb obear" , 
                                                                                    "Open Small" = "wb mitchell") ,
                                                                                  "west brook" ) ,
                                                                     radioButtons("seasonNoneNone" ,
                                                                                  "Season" ,
                                                                                  c('Spring' = '1' ,
                                                                                    'Summer' = '2' ,
                                                                                    'Fall' = '3' ,
                                                                                    'Winter' = '4') ,
                                                                                  '1' ))))),
                               
                               
                               wellPanel(
                                 
                                 splitLayout(
                                   radioButtons('facet1' , 
                                                'Facet One' , 
                                                c ('Age' , 'River' , 'Season' , 'Species' , 'None') , 'None'),
                                   radioButtons('facet2' , 
                                                'Facet Two' , 
                                                c ('Age' , 'River' , 'Season' , 'Species' , 'None') , 'None'))
                               ),
                               fluidRow(
                                 column(3 , tags$h3("Graph_Controls"))),
                               wellPanel( 
                                 
                                 splitLayout(
                                   radioButtons("aXis" ,
                                                "X-Axis" , 
                                                c("Stream Temperature" = "temp"  , 
                                                  "Stream Flow" = "flow" , 
                                                  "Estimated Abundance" = "count" , 
                                                  "Fish Length" = "len" ) ,
                                                "temp" ) ,
                                   radioButtons("color" ,
                                                "Color" , 
                                                c("Stream Temperature" = "temp" , 
                                                  "Stream Flow" = "flow" , 
                                                  "Estimated Abundance" =  "count" , 
                                                  "Fish Length" = "len" ) ,
                                                "flow" )) ,
                                 # checkboxGroupInput("riverB" ,
                                 #"Slider" , 
                                 #c("temp" , "flow" , "count") ,
                                 #"count" )) ,
                                 
                                 
                                 conditionalPanel(condition = "input.aXis == 'temp'",
                                                  conditionalPanel(condition = "input.color == 'flow'",
                                                                   sliderInput("changeInTempCountOne",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInTempLengthOne",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 conditionalPanel(condition = "input.aXis == 'temp'",
                                                  conditionalPanel(condition = "input.color == 'count'",
                                                                   sliderInput("changeInTempFlowOne",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInTempLengthTwo",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 conditionalPanel(condition = "input.aXis == 'temp'",
                                                  conditionalPanel(condition = "input.color == 'len'",
                                                                   sliderInput("changeInTempCountTwo",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),
                                                                   sliderInput("changeInTempFlowTwo",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 
                                 
                                 
                                 
                                 conditionalPanel(condition = "input.aXis == 'flow'",
                                                  conditionalPanel(condition = "input.color == 'count'",
                                                                   sliderInput("changeInFlowLengthOne",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInFlowTempOne",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 conditionalPanel(condition = "input.aXis == 'flow'",
                                                  conditionalPanel(condition = "input.color == 'temp'",
                                                                   sliderInput("changeInFlowLengthTwo",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInFlowCountOne",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 conditionalPanel(condition = "input.aXis == 'flow'",
                                                  conditionalPanel(condition = "input.color == 'len'",
                                                                   sliderInput("changeInFlowTempTwo",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),
                                                                   sliderInput("changeInFlowCountTwo",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 
                                 
                                 conditionalPanel(condition = "input.aXis == 'count'",
                                                  conditionalPanel(condition = "input.color == 'flow'",
                                                                   sliderInput("changeInCountLengthOne",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInCountTempOne",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 conditionalPanel(condition = "input.aXis == 'count'",
                                                  conditionalPanel(condition = "input.color == 'temp'",
                                                                   sliderInput("changeInCountLengthTwo",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInCountFlowOne",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 conditionalPanel(condition = "input.aXis == 'count'",
                                                  conditionalPanel(condition = "input.color == 'len'",
                                                                   sliderInput("changeInCountTempTwo",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),
                                                                   sliderInput("changeInCountFlowTwo",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 
                                 
                                 conditionalPanel(condition = "input.aXis == 'len'",
                                                  conditionalPanel(condition = "input.color == 'flow'",
                                                                   sliderInput("changeInLengthCountOne",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInLengthTempOne",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 conditionalPanel(condition = "input.aXis == 'len'",
                                                  conditionalPanel(condition = "input.color == 'temp'",
                                                                   sliderInput("changeInLengthCountTwo",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInLengthFlowOne",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 conditionalPanel(condition = "input.aXis == 'len'",
                                                  conditionalPanel(condition = "input.color == 'count'",
                                                                   sliderInput("changeInLengthTempTwo",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),
                                                                   sliderInput("changeInLengthFlowTwo",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))), 
                                 sliderInput("slider2B", label = h4("Iterations"), min = 10, 
                                             max = 1500, value =  1000)
                               )),
                        
                        
                        
                        
                        
                        # Show a plot of the generated distribution
                        column(9,
                               withSpinner( plotOutput("plot1B" , height = "700px"))
                        )
                      )
             )))

